### ISSUE TITLE
Colab crashes on launch

### ISSUE THREAD

**Issue by BillTribble** [GeeveGeorge/Stable-Craiyon#1]
"Your session crashed for an unknown reason."
WARNING:root:kernel a2d071e6-d71d-4338-8dec-352d2617cda3 restarted

**Comment by GeeveGeorge** [comment]
@BillTribble , that is supposed to happen. You can just ignore the warning and continue running the next cells in sequence.
Because , as soon as you run the first cell , the colab notebook resets so as to clear GPU VRAM.

Since Craiyon + Stable Diffusion are both GPU heavy tools , we have to clear the VRAM (so as to make it work in colab free tier)

I have made a tutorial video and I explain how to use the notebook here :
https://www.youtube.com/watch?v=7dbyqg7XSJ8

**Comment by BillTribble** [comment]
ahh sorry! Thanks for clarifying :)
